# Generated by Django 2.2.5 on 2021-01-11 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='subjct',
        ),
    ]
