# Generated by Django 2.2.5 on 2021-01-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0002_remove_contactform_subjct'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='date',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='contactform',
            name='time',
            field=models.CharField(default='', max_length=12),
        ),
    ]
